pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Print Message') {
            steps {
                echo 'Printing the message stage'
            }
        }
        stage('Final') {
            steps {
                echo 'Final Stage done, signing off'
            }
        }
    }
}
